# CMake generated Testfile for 
# Source directory: C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint
# Build directory: C:/IDA/BUILDDIR/examples/sunnonlinsol/fixedpoint
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunnonlinsol_fixedpoint "C:/IDA/BUILDDIR/bin/Debug/test_sunnonlinsol_fixedpoint.exe")
  set_tests_properties(test_sunnonlinsol_fixedpoint PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunnonlinsol_fixedpoint "C:/IDA/BUILDDIR/bin/Release/test_sunnonlinsol_fixedpoint.exe")
  set_tests_properties(test_sunnonlinsol_fixedpoint PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunnonlinsol_fixedpoint "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunnonlinsol_fixedpoint.exe")
  set_tests_properties(test_sunnonlinsol_fixedpoint PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunnonlinsol_fixedpoint "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunnonlinsol_fixedpoint.exe")
  set_tests_properties(test_sunnonlinsol_fixedpoint PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
else()
  add_test(test_sunnonlinsol_fixedpoint NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunnonlinsol_fixedpoint_2 "C:/IDA/BUILDDIR/bin/Debug/test_sunnonlinsol_fixedpoint.exe" "2")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunnonlinsol_fixedpoint_2 "C:/IDA/BUILDDIR/bin/Release/test_sunnonlinsol_fixedpoint.exe" "2")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunnonlinsol_fixedpoint_2 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunnonlinsol_fixedpoint.exe" "2")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunnonlinsol_fixedpoint_2 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunnonlinsol_fixedpoint.exe" "2")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
else()
  add_test(test_sunnonlinsol_fixedpoint_2 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunnonlinsol_fixedpoint_2_0.5 "C:/IDA/BUILDDIR/bin/Debug/test_sunnonlinsol_fixedpoint.exe" "2" "0.5")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2_0.5 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunnonlinsol_fixedpoint_2_0.5 "C:/IDA/BUILDDIR/bin/Release/test_sunnonlinsol_fixedpoint.exe" "2" "0.5")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2_0.5 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunnonlinsol_fixedpoint_2_0.5 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunnonlinsol_fixedpoint.exe" "2" "0.5")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2_0.5 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunnonlinsol_fixedpoint_2_0.5 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunnonlinsol_fixedpoint.exe" "2" "0.5")
  set_tests_properties(test_sunnonlinsol_fixedpoint_2_0.5 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;77;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunnonlinsol/fixedpoint/CMakeLists.txt;0;")
else()
  add_test(test_sunnonlinsol_fixedpoint_2_0.5 NOT_AVAILABLE)
endif()
