# CMake generated Testfile for 
# Source directory: C:/IDA/ida-6.5.1/examples/sunlinsol/dense
# Build directory: C:/IDA/BUILDDIR/examples/sunlinsol/dense
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_dense_10_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunlinsol_dense.exe" "10" "0")
  set_tests_properties(test_sunlinsol_dense_10_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_dense_10_0 "C:/IDA/BUILDDIR/bin/Release/test_sunlinsol_dense.exe" "10" "0")
  set_tests_properties(test_sunlinsol_dense_10_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_dense_10_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunlinsol_dense.exe" "10" "0")
  set_tests_properties(test_sunlinsol_dense_10_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_dense_10_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunlinsol_dense.exe" "10" "0")
  set_tests_properties(test_sunlinsol_dense_10_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
else()
  add_test(test_sunlinsol_dense_10_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_dense_100_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunlinsol_dense.exe" "100" "0")
  set_tests_properties(test_sunlinsol_dense_100_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_dense_100_0 "C:/IDA/BUILDDIR/bin/Release/test_sunlinsol_dense.exe" "100" "0")
  set_tests_properties(test_sunlinsol_dense_100_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_dense_100_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunlinsol_dense.exe" "100" "0")
  set_tests_properties(test_sunlinsol_dense_100_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_dense_100_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunlinsol_dense.exe" "100" "0")
  set_tests_properties(test_sunlinsol_dense_100_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
else()
  add_test(test_sunlinsol_dense_100_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_dense_500_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunlinsol_dense.exe" "500" "0")
  set_tests_properties(test_sunlinsol_dense_500_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_dense_500_0 "C:/IDA/BUILDDIR/bin/Release/test_sunlinsol_dense.exe" "500" "0")
  set_tests_properties(test_sunlinsol_dense_500_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_dense_500_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunlinsol_dense.exe" "500" "0")
  set_tests_properties(test_sunlinsol_dense_500_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_dense_500_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunlinsol_dense.exe" "500" "0")
  set_tests_properties(test_sunlinsol_dense_500_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
else()
  add_test(test_sunlinsol_dense_500_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_dense_1000_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunlinsol_dense.exe" "1000" "0")
  set_tests_properties(test_sunlinsol_dense_1000_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_dense_1000_0 "C:/IDA/BUILDDIR/bin/Release/test_sunlinsol_dense.exe" "1000" "0")
  set_tests_properties(test_sunlinsol_dense_1000_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_dense_1000_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunlinsol_dense.exe" "1000" "0")
  set_tests_properties(test_sunlinsol_dense_1000_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_dense_1000_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunlinsol_dense.exe" "1000" "0")
  set_tests_properties(test_sunlinsol_dense_1000_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunlinsol/dense/CMakeLists.txt;0;")
else()
  add_test(test_sunlinsol_dense_1000_0 NOT_AVAILABLE)
endif()
