# CMake generated Testfile for 
# Source directory: C:/IDA/ida-6.5.1/examples/sunmatrix/band
# Build directory: C:/IDA/BUILDDIR/examples/sunmatrix/band
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_band_10_2_3_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_band.exe" "10" "2" "3" "0")
  set_tests_properties(test_sunmatrix_band_10_2_3_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_band_10_2_3_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_band.exe" "10" "2" "3" "0")
  set_tests_properties(test_sunmatrix_band_10_2_3_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_band_10_2_3_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_band.exe" "10" "2" "3" "0")
  set_tests_properties(test_sunmatrix_band_10_2_3_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_band_10_2_3_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_band.exe" "10" "2" "3" "0")
  set_tests_properties(test_sunmatrix_band_10_2_3_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_band_10_2_3_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_band_300_7_4_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_band.exe" "300" "7" "4" "0")
  set_tests_properties(test_sunmatrix_band_300_7_4_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_band_300_7_4_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_band.exe" "300" "7" "4" "0")
  set_tests_properties(test_sunmatrix_band_300_7_4_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_band_300_7_4_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_band.exe" "300" "7" "4" "0")
  set_tests_properties(test_sunmatrix_band_300_7_4_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_band_300_7_4_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_band.exe" "300" "7" "4" "0")
  set_tests_properties(test_sunmatrix_band_300_7_4_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_band_300_7_4_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_band_1000_8_8_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_band.exe" "1000" "8" "8" "0")
  set_tests_properties(test_sunmatrix_band_1000_8_8_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_band_1000_8_8_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_band.exe" "1000" "8" "8" "0")
  set_tests_properties(test_sunmatrix_band_1000_8_8_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_band_1000_8_8_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_band.exe" "1000" "8" "8" "0")
  set_tests_properties(test_sunmatrix_band_1000_8_8_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_band_1000_8_8_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_band.exe" "1000" "8" "8" "0")
  set_tests_properties(test_sunmatrix_band_1000_8_8_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_band_1000_8_8_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_band_5000_3_20_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_band.exe" "5000" "3" "20" "0")
  set_tests_properties(test_sunmatrix_band_5000_3_20_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_band_5000_3_20_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_band.exe" "5000" "3" "20" "0")
  set_tests_properties(test_sunmatrix_band_5000_3_20_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_band_5000_3_20_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_band.exe" "5000" "3" "20" "0")
  set_tests_properties(test_sunmatrix_band_5000_3_20_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_band_5000_3_20_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_band.exe" "5000" "3" "20" "0")
  set_tests_properties(test_sunmatrix_band_5000_3_20_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/band/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_band_5000_3_20_0 NOT_AVAILABLE)
endif()
