# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SUNDIALS::generic_static SUNDIALS::generic_shared SUNDIALS::nvecserial_static SUNDIALS::nvecserial_shared SUNDIALS::nvecmanyvector_static SUNDIALS::nvecmanyvector_shared SUNDIALS::sunmatrixband_static SUNDIALS::sunmatrixband_shared SUNDIALS::sunmatrixdense_static SUNDIALS::sunmatrixdense_shared SUNDIALS::sunmatrixsparse_static SUNDIALS::sunmatrixsparse_shared SUNDIALS::sunlinsolband_static SUNDIALS::sunlinsolband_shared SUNDIALS::sunlinsoldense_static SUNDIALS::sunlinsoldense_shared SUNDIALS::sunlinsolpcg_static SUNDIALS::sunlinsolpcg_shared SUNDIALS::sunlinsolspbcgs_static SUNDIALS::sunlinsolspbcgs_shared SUNDIALS::sunlinsolspfgmr_static SUNDIALS::sunlinsolspfgmr_shared SUNDIALS::sunlinsolspgmr_static SUNDIALS::sunlinsolspgmr_shared SUNDIALS::sunlinsolsptfqmr_static SUNDIALS::sunlinsolsptfqmr_shared SUNDIALS::sunnonlinsolnewton_static SUNDIALS::sunnonlinsolnewton_shared SUNDIALS::sunnonlinsolfixedpoint_static SUNDIALS::sunnonlinsolfixedpoint_shared SUNDIALS::ida_static SUNDIALS::ida_shared)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SUNDIALS::generic_static
add_library(SUNDIALS::generic_static STATIC IMPORTED)

set_target_properties(SUNDIALS::generic_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::generic_shared
add_library(SUNDIALS::generic_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::generic_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::nvecserial_static
add_library(SUNDIALS::nvecserial_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::nvecserial_shared
add_library(SUNDIALS::nvecserial_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::nvecmanyvector_static
add_library(SUNDIALS::nvecmanyvector_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::nvecmanyvector_shared
add_library(SUNDIALS::nvecmanyvector_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunmatrixband_static
add_library(SUNDIALS::sunmatrixband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunmatrixband_shared
add_library(SUNDIALS::sunmatrixband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunmatrixdense_static
add_library(SUNDIALS::sunmatrixdense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunmatrixdense_shared
add_library(SUNDIALS::sunmatrixdense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunmatrixsparse_static
add_library(SUNDIALS::sunmatrixsparse_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunmatrixsparse_shared
add_library(SUNDIALS::sunmatrixsparse_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolband_static
add_library(SUNDIALS::sunlinsolband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::sunmatrixband_shared"
)

# Create imported target SUNDIALS::sunlinsolband_shared
add_library(SUNDIALS::sunlinsolband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::sunmatrixband_shared"
)

# Create imported target SUNDIALS::sunlinsoldense_static
add_library(SUNDIALS::sunlinsoldense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::sunmatrixdense_shared"
)

# Create imported target SUNDIALS::sunlinsoldense_shared
add_library(SUNDIALS::sunlinsoldense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::sunmatrixdense_shared"
)

# Create imported target SUNDIALS::sunlinsolpcg_static
add_library(SUNDIALS::sunlinsolpcg_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolpcg_shared
add_library(SUNDIALS::sunlinsolpcg_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_static
add_library(SUNDIALS::sunlinsolspbcgs_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_shared
add_library(SUNDIALS::sunlinsolspbcgs_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_static
add_library(SUNDIALS::sunlinsolspfgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_shared
add_library(SUNDIALS::sunlinsolspfgmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolspgmr_static
add_library(SUNDIALS::sunlinsolspgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolspgmr_shared
add_library(SUNDIALS::sunlinsolspgmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_static
add_library(SUNDIALS::sunlinsolsptfqmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_shared
add_library(SUNDIALS::sunlinsolsptfqmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_static
add_library(SUNDIALS::sunnonlinsolnewton_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_shared
add_library(SUNDIALS::sunnonlinsolnewton_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_static
add_library(SUNDIALS::sunnonlinsolfixedpoint_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_shared
add_library(SUNDIALS::sunnonlinsolfixedpoint_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::ida_static
add_library(SUNDIALS::ida_static STATIC IMPORTED)

set_target_properties(SUNDIALS::ida_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Create imported target SUNDIALS::ida_shared
add_library(SUNDIALS::ida_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::ida_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/IDA/ida-6.5.1/include;C:/IDA/BUILDDIR/include;C:/IDA/ida-6.5.1/src/sundials"
)

# Import target "SUNDIALS::generic_static" for configuration "Debug"
set_property(TARGET SUNDIALS::generic_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::generic_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_generic.lib"
  )

# Import target "SUNDIALS::generic_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::generic_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::generic_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_generic.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_generic.dll"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "Debug"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_nvecserial.lib"
  )

# Import target "SUNDIALS::nvecserial_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::nvecserial_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_nvecserial.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_nvecserial.dll"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "Debug"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_nvecmanyvector.lib"
  )

# Import target "SUNDIALS::nvecmanyvector_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::nvecmanyvector_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_nvecmanyvector.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_nvecmanyvector.dll"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixband.lib"
  )

# Import target "SUNDIALS::sunmatrixband_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunmatrixband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixband.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixband.dll"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixdense.lib"
  )

# Import target "SUNDIALS::sunmatrixdense_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunmatrixdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixdense.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixdense.dll"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixsparse.lib"
  )

# Import target "SUNDIALS::sunmatrixsparse_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunmatrixsparse_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixsparse.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunmatrixsparse.dll"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolband.lib"
  )

# Import target "SUNDIALS::sunlinsolband_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolband.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolband.dll"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsoldense.lib"
  )

# Import target "SUNDIALS::sunlinsoldense_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsoldense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsoldense.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsoldense.dll"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolpcg.lib"
  )

# Import target "SUNDIALS::sunlinsolpcg_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolpcg_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolpcg.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolpcg.dll"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspbcgs.lib"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspbcgs.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspbcgs.dll"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspfgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspfgmr.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspfgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspgmr_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolspgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspgmr.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolspgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolsptfqmr.lib"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolsptfqmr.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunlinsolsptfqmr.dll"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunnonlinsolnewton.lib"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunnonlinsolnewton.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunnonlinsolnewton.dll"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "Debug"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunnonlinsolfixedpoint.lib"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunnonlinsolfixedpoint.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_sunnonlinsolfixedpoint.dll"
  )

# Import target "SUNDIALS::ida_static" for configuration "Debug"
set_property(TARGET SUNDIALS::ida_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::ida_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_ida.lib"
  )

# Import target "SUNDIALS::ida_shared" for configuration "Debug"
set_property(TARGET SUNDIALS::ida_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SUNDIALS::ida_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_ida.lib"
  IMPORTED_LOCATION_DEBUG "C:/IDA/BUILDDIR/bin/Debug/sundials_ida.dll"
  )

# Import target "SUNDIALS::generic_static" for configuration "Release"
set_property(TARGET SUNDIALS::generic_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::generic_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_generic.lib"
  )

# Import target "SUNDIALS::generic_shared" for configuration "Release"
set_property(TARGET SUNDIALS::generic_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::generic_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_generic.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_generic.dll"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "Release"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_nvecserial.lib"
  )

# Import target "SUNDIALS::nvecserial_shared" for configuration "Release"
set_property(TARGET SUNDIALS::nvecserial_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_nvecserial.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_nvecserial.dll"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "Release"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_nvecmanyvector.lib"
  )

# Import target "SUNDIALS::nvecmanyvector_shared" for configuration "Release"
set_property(TARGET SUNDIALS::nvecmanyvector_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_nvecmanyvector.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_nvecmanyvector.dll"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixband.lib"
  )

# Import target "SUNDIALS::sunmatrixband_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixband.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixband.dll"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixdense.lib"
  )

# Import target "SUNDIALS::sunmatrixdense_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixdense.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixdense.dll"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixsparse.lib"
  )

# Import target "SUNDIALS::sunmatrixsparse_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixsparse_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixsparse.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunmatrixsparse.dll"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolband.lib"
  )

# Import target "SUNDIALS::sunlinsolband_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolband.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolband.dll"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsoldense.lib"
  )

# Import target "SUNDIALS::sunlinsoldense_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsoldense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsoldense.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsoldense.dll"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolpcg.lib"
  )

# Import target "SUNDIALS::sunlinsolpcg_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolpcg_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolpcg.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolpcg.dll"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspbcgs.lib"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspbcgs.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspbcgs.dll"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspfgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspfgmr.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspfgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspgmr_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspgmr.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolspgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolsptfqmr.lib"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolsptfqmr.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunlinsolsptfqmr.dll"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunnonlinsolnewton.lib"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunnonlinsolnewton.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunnonlinsolnewton.dll"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunnonlinsolfixedpoint.lib"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_shared" for configuration "Release"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunnonlinsolfixedpoint.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_sunnonlinsolfixedpoint.dll"
  )

# Import target "SUNDIALS::ida_static" for configuration "Release"
set_property(TARGET SUNDIALS::ida_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::ida_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_ida.lib"
  )

# Import target "SUNDIALS::ida_shared" for configuration "Release"
set_property(TARGET SUNDIALS::ida_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::ida_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_ida.lib"
  IMPORTED_LOCATION_RELEASE "C:/IDA/BUILDDIR/bin/Release/sundials_ida.dll"
  )

# Import target "SUNDIALS::generic_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::generic_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::generic_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_generic.lib"
  )

# Import target "SUNDIALS::generic_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::generic_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::generic_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_generic.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_generic.dll"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_nvecserial.lib"
  )

# Import target "SUNDIALS::nvecserial_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::nvecserial_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_nvecserial.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_nvecserial.dll"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_nvecmanyvector.lib"
  )

# Import target "SUNDIALS::nvecmanyvector_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::nvecmanyvector_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_nvecmanyvector.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_nvecmanyvector.dll"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixband.lib"
  )

# Import target "SUNDIALS::sunmatrixband_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunmatrixband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixband.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixband.dll"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixdense.lib"
  )

# Import target "SUNDIALS::sunmatrixdense_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunmatrixdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixdense.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixdense.dll"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixsparse.lib"
  )

# Import target "SUNDIALS::sunmatrixsparse_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunmatrixsparse_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixsparse.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunmatrixsparse.dll"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolband.lib"
  )

# Import target "SUNDIALS::sunlinsolband_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolband.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolband.dll"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsoldense.lib"
  )

# Import target "SUNDIALS::sunlinsoldense_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsoldense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsoldense.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsoldense.dll"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolpcg.lib"
  )

# Import target "SUNDIALS::sunlinsolpcg_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolpcg_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolpcg.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolpcg.dll"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspbcgs.lib"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspbcgs.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspbcgs.dll"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspfgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspfgmr.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspfgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspgmr_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolspgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspgmr.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolspgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolsptfqmr.lib"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolsptfqmr.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunlinsolsptfqmr.dll"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunnonlinsolnewton.lib"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunnonlinsolnewton.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunnonlinsolnewton.dll"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunnonlinsolfixedpoint.lib"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunnonlinsolfixedpoint.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_sunnonlinsolfixedpoint.dll"
  )

# Import target "SUNDIALS::ida_static" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::ida_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::ida_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_ida.lib"
  )

# Import target "SUNDIALS::ida_shared" for configuration "MinSizeRel"
set_property(TARGET SUNDIALS::ida_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SUNDIALS::ida_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_ida.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/IDA/BUILDDIR/bin/MinSizeRel/sundials_ida.dll"
  )

# Import target "SUNDIALS::generic_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::generic_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::generic_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_generic.lib"
  )

# Import target "SUNDIALS::generic_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::generic_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::generic_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_generic.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_generic.dll"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_nvecserial.lib"
  )

# Import target "SUNDIALS::nvecserial_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecserial_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_nvecserial.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_nvecserial.dll"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_nvecmanyvector.lib"
  )

# Import target "SUNDIALS::nvecmanyvector_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecmanyvector_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_nvecmanyvector.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_nvecmanyvector.dll"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixband.lib"
  )

# Import target "SUNDIALS::sunmatrixband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixband.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixband.dll"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixdense.lib"
  )

# Import target "SUNDIALS::sunmatrixdense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixdense.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixdense.dll"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixsparse.lib"
  )

# Import target "SUNDIALS::sunmatrixsparse_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixsparse_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixsparse.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunmatrixsparse.dll"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolband.lib"
  )

# Import target "SUNDIALS::sunlinsolband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolband.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolband.dll"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsoldense.lib"
  )

# Import target "SUNDIALS::sunlinsoldense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsoldense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsoldense.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsoldense.dll"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolpcg.lib"
  )

# Import target "SUNDIALS::sunlinsolpcg_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolpcg_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolpcg.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolpcg.dll"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspbcgs.lib"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspbcgs.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspbcgs.dll"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspfgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspfgmr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspfgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspgmr.lib"
  )

# Import target "SUNDIALS::sunlinsolspgmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspgmr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolspgmr.dll"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolsptfqmr.lib"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolsptfqmr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunlinsolsptfqmr.dll"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunnonlinsolnewton.lib"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunnonlinsolnewton.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunnonlinsolnewton.dll"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunnonlinsolfixedpoint.lib"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunnonlinsolfixedpoint.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_sunnonlinsolfixedpoint.dll"
  )

# Import target "SUNDIALS::ida_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::ida_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::ida_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_ida.lib"
  )

# Import target "SUNDIALS::ida_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::ida_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::ida_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_ida.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/IDA/BUILDDIR/bin/RelWithDebInfo/sundials_ida.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
