# CMake generated Testfile for 
# Source directory: C:/IDA/ida-6.5.1/examples/sunmatrix/sparse
# Build directory: C:/IDA/BUILDDIR/examples/sunmatrix/sparse
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_sparse.exe" "400" "400" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_400_400_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_sparse.exe" "400" "400" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_400_400_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_sparse.exe" "400" "400" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_400_400_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_sparse.exe" "400" "400" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_400_400_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_sparse_400_400_0_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_sparse.exe" "450" "450" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_450_450_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_sparse.exe" "450" "450" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_450_450_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_sparse.exe" "450" "450" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_450_450_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_sparse.exe" "450" "450" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_450_450_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_sparse_450_450_1_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_sparse.exe" "200" "1000" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_200_1000_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_sparse.exe" "200" "1000" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_200_1000_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_sparse.exe" "200" "1000" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_200_1000_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_sparse.exe" "200" "1000" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_200_1000_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_sparse_200_1000_0_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_sparse.exe" "6000" "350" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_6000_350_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_sparse.exe" "6000" "350" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_6000_350_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_sparse.exe" "6000" "350" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_6000_350_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_sparse.exe" "6000" "350" "0" "0")
  set_tests_properties(test_sunmatrix_sparse_6000_350_0_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_sparse_6000_350_0_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_sparse.exe" "500" "5000" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_500_5000_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_sparse.exe" "500" "5000" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_500_5000_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_sparse.exe" "500" "5000" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_500_5000_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_sparse.exe" "500" "5000" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_500_5000_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_sparse_500_5000_1_0 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/IDA/BUILDDIR/bin/Debug/test_sunmatrix_sparse.exe" "4000" "800" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_4000_800_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/IDA/BUILDDIR/bin/Release/test_sunmatrix_sparse.exe" "4000" "800" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_4000_800_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/IDA/BUILDDIR/bin/MinSizeRel/test_sunmatrix_sparse.exe" "4000" "800" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_4000_800_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/IDA/BUILDDIR/bin/RelWithDebInfo/test_sunmatrix_sparse.exe" "4000" "800" "1" "0")
  set_tests_properties(test_sunmatrix_sparse_4000_800_1_0 PROPERTIES  _BACKTRACE_TRIPLES "C:/IDA/ida-6.5.1/cmake/macros/SundialsAddTest.cmake;183;add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;79;sundials_add_test;C:/IDA/ida-6.5.1/examples/sunmatrix/sparse/CMakeLists.txt;0;")
else()
  add_test(test_sunmatrix_sparse_4000_800_1_0 NOT_AVAILABLE)
endif()
